routes/web.php
        $users[] = array_pop($split);
        
    }

    if(!empty($users)) {
        
        $info = [
            'user_id' => $user_id,
            'status' => $status,
            'game_name' => Auth::user()->selectedGame()['game'],
            'platform_name' => Auth::user()->selectedGame()['platform'],
        ];

        $users = User::find($users);

        if($users)
            foreach($users as $user){
                if($user->id != Auth::user()->id)
                    broadcast(new \App\Events\LobbyStatusChanged($user->id,$info));
            }
            
        
    }

    return response()->json(['status'=>$status]);
})->name('lobbystatus');

Route::get('/poczekalnia/mark/{status}/{user_id}','Lobby\LobbyController@markInfo')->name('lobby.mark.info');

Route::post('/poczekalnia/info/set','Lobby\LobbyController@setInfo')->name('lobby.set.info');
Route::get('/poczekalnia','Lobby\LobbyController@show')->name('lobby');


Route::get('/user/{user_id}/status', function($user_id) {
    $user = User::find($user_id);

    $status = $user->getStatus();

    return response()->json($status);
})->name('user_status');

Route::prefix('admin')->name('admin.')->group(function () {

    Route::get('dashboard', 'Admin\AdminController@dashboardShow')->name('dashboard');
    
    Route::get('user', 'Admin\UserController@list')->name('user.list');
    Route::get('user/{id}','Admin\UserController@show')->name('user.show');

    Route::get('menu', 'Admin\AdminController@menuShow')->name('menu');
    Route::get('settings', 'Admin\AdminController@settingsShow')->name('settings');
    Route::get('language', 'Admin\AdminController@languageShow')->name('language');
    Route::get('posts', 'Admin\AdminController@postListShow')->name('posts');
    Route::get('tickets', 'Admin\AdminController@ticketsListShow')->name('tickets');
    
    Route::get('game/list','Admin\GamesController@index')->name('game.list');
    Route::get('game/create', 'Admin\GamesController@createGame')->name('game.create');
    Route::post('game/save', 'Admin\GamesController@saveGame')->name('game.save');
    Route::get('game/scrapper', 'Admin\ScrapperController@index')->name('game.scrapper');
    Route::get('game/scrapper/scrap', 'Admin\ScrapperController@scrap')->name('game.scrapper.scrap');
    Route::get('game/{id}/edit', 'Admin\GamesController@editGame')->name('game.edit');
    Route::post('game/{id}/update', 'Admin\GamesController@updateGame')->name('game.update');
    Route::post('game/{id}/delete', 'Admin\GamesController@deleteGame')->name('game.delete');
    Route::get('game/{id}','Admin\GamesController@showGame')->name('game.show');
    
    
    //Posts
    Route::get('post', 'Admin\PostController@list')->name('post.list');
    Route::get('post/create', 'Admin\PostController@create')->name('post.create');
    Route::post('post/store', 'Admin\PostController@store')->name('post.store');
    Route::get('post/{id}/edit', 'Admin\PostController@edit')->name('post.edit');
    Route::get('post/{id}/update', 'Admin\PostController@update')->name('post.update');
    Route::get('post/{id}/delete', 'Admin\PostController@delete')->name('post.delete');
    Route::get('post/{id}', 'Admin\PostController@show')->name('post.show');

    Route::get('stats/users/append', 'Admin\AdminController@getUsersDailyCount')->name('stats.users.append');
    Route::get('stats/posts/append', 'Admin\AdminController@getPostsDailyCount')->name('stats.posts.append');
    Route::get('stats/comments/append', 'Admin\AdminController@getCommentsDailyCount')->name('stats.comments.append');
    Route::get('stats/logins/append', 'Admin\AdminController@getLoginsDailyCount')->name('stats.logins.append');
    
    Route::get('stats/users/count', 'Admin\AdminDashboardController@countUsers')->name('stats.users.count');

    Route::get('tickets', 'Admin\TicketsController@list')->name('tickets.list');
    Route::get('tickets/{id}', 'Admin\TicketsController@show')->name('tickets.show');
    Route::get('tickets/{id}/close', 'Admin\TicketsController@closeTicket')->name('tickets.close');
    Route::get('tickets/{id}/open', 'Admin\TicketsController@openTicket')->name('tickets.open');
    Route::post('tickets/wyslij','Admin\TicketsController@messageSend')->name('tickets.send');

    Route::get('giveaway', 'Admin\GiveawayController@list')->name('giveaway.list');
    Route::get('giveaway/create', 'Admin\GiveawayController@create')->name('giveaway.create');
    Route::post('giveaway/store', 'Admin\GiveawayController@store')->name('giveaway.store');
    Route::get('giveaway/{id}/edit', 'Admin\GiveawayController@edit')->name('giveaway.edit');
    Route::get('giveaway/{id}/update', 'Admin\GiveawayController@update')->name('giveaway.update');
    Route::get('giveaway/{id}/delete', 'Admin\GiveawayController@delete')->name('giveaway.delete');
    Route::get('giveaway/{id}/activate', 'Admin\GiveawayController@activate')->name('giveaway.activate');
    Route::get('giveaway/{id}/deactivate', 'Admin\GiveawayController@deactivate')->name('giveaway.deactivate');
    Route::get('giveaway/{id}', 'Admin\GiveawayController@show')->name('giveaway.show');

    Route::get('quest', 'Admin\QuestController@list')->name('quest.list');
    Route::get('quest/create', 'Admin\QuestController@create')->name('quest.create');
    Route::post('quest/store', 'Admin\QuestController@store')->name('quest.store');
    Route::get('quest/{id}/edit', 'Admin\QuestController@edit')->name('quest.edit');
    Route::get('quest/{id}/update', 'Admin\QuestController@update')->name('quest.update');
    Route::get('quest/{id}/delete', 'Admin\QuestController@delete')->name('quest.delete');
    Route::get('quest/{id}/activate', 'Admin\QuestController@activate')->name('quest.activate');
    Route::get('quest/{id}/deactivate', 'Admin\QuestController@deactivate')->name('quest.deactivate');
    Route::get('quest/{id}', 'Admin\QuestController@show')->name('quest.show');
});

Route::prefix('helper')->name('help.')->group(function () {
    Route::get('voivodeship', 'HelperController@getVoivodeships')->name('voivodeships');
    Route::get('cities/{voivodeship_id}', 'HelperController@getCities')->name('cities');
    Route::get('games', 'HelperController@getGames')->name('games');
    Route::get('platforms/{game_id}', 'HelperController@getGamesPlatform')->name('platforms');
    Route::get('teams/{clan_id}', 'HelperController@getClanTeams')->name('teams');
    Route::get('members/{clan_id}', 'HelperController@getTeamMembers')->name('members');
    Route::get('set/friends/list','HelperController@setFriendList')->name('friend.list');

});


Route::prefix('mecz')->name('match.')->group(function () {
    Route::prefix('towarzyski')->name('friendly.')->group(function() {
        
        Route::get('stworz','Match\FriendlyController@createFriendly')->name('create');
        Route::post('zapisz','Match\FriendlyController@saveFriendly')->name('save');
        
        Route::get('tablica','Match\FriendlyController@showFriendly')->name('list');
        Route::post('tablica','Match\FriendlyController@doSearching')->name('list.search');
        
        Route::get('zobacz/{id}', 'Match\FriendlyController@showMatch')->name('show');
        Route::get('edytuj/{id}', 'Match\FriendlyController@editMatch')->name('edit');
        Route::post('edytuj','Match\FriendlyController@updateMatch')->name('update');
        Route::get('usun/{ids}','Match\FriendlyController@deleteMatch')->name('delete');
        Route::post('dolacz','Match\FriendlyController@joinMatch')->name('join');
        Route::post('potwierdz','Match\FriendlyController@applyMatch')->name('apply');
        Route::get('akceptuj/{id}','Match\FriendlyController@acceptAplication')->name('accept');
        Route::get('podsumowanie','Match\FriendlyController@confirmFriendly')->name('confirm');
        Route::get('cancel/{id}','Match\FriendlyController@cancelMatch')->name('cancel');

        Route::get('aktywne','Match\FriendlyController@showActive')->name('show.active');
        Route::get('otwarte','Match\FriendlyController@showOpen')->name('show.open');
        Route::get('zamkniete','Match\FriendlyController@showClosed')->name('show.closed');
        Route::get('edit/stop/{id}','Match\FriendlyController@stopEdit')->name('change.edit');
        Route::post('wyslij/wynik','Match\FriendlyController@sendResult')->name('send.result');
        Route::get('aplikacja/wycofaj/{aplication_id}/{match_id}','Match\FriendlyController@aplicationCancel')->name('aplication.cancel');


        Route::get('akceptuj/wynik/{match_id}','Match\FriendlyController@acceptResult')->name('accept.result');
        Route::get('odrzuc/wynik/{match_id}','Match\FriendlyController@rejectResult')->name('reject.result');

        Route::post('archiwum/szukaj','Match\FriendlyController@archiveSearching')->name('archive.search');
        Route::get('archiwum/szukaj','Match\FriendlyController@showArchive')->name('archive.search.get');
        Route::get('archiwum','Match\FriendlyController@showArchive')->name('show.archive');
        
    });


});

Route::get('/public/bg_avatar', function() {
    $image = asset('images/logo/BG_Avatar.png');
    return Image::make($image)->response('png');
});
Route::get('regulamin','PageController@showPage')->name('regulamin');
Route::get('polityka','PageController@showPage')->name('polityka_prywatnosci');
Route::get('kontakt','PageController@showContact')->name('kontakt');
Route::post('kontakt/wyslij','PageController@sendForm')->name('kontakt.wyslij');


/*
Route::prefix('giveaway')->name('giveaway.')->group(function () {

    Route::prefix('/tickets')->name('tickets.')->group(function () {
        Route::get('','Giveaway\Tickets\TicketsController@list')->name('list');
        
    
        
    });

    Route::get('','Giveaway\GiveawayController@list')->name('list');
    Route::get('{id}/join','Giveaway\GiveawayController@join')->name('join');
    Route::get('{id}','Giveaway\GiveawayController@show')->name('show');

app/Giveaway.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use Auth;

class Giveaway extends Model
{

    protected $table = 'giveaway';

    protected $fillable = ['title','description','main_img','ending_at','status','carousel_img'];


    public $joinAvalible = true;

    public function userJoined() {
        $user = Auth::user();



        return false;
    }

    public function rules() {
        return $this->belongsToMany('App\GiveawayRules','giveaway_rules_pivot','giveaway_id','rule_id');
    }

    public function participants() {
        return $this->belongsToMany('App\User','giveaway_joins','giveaway_id','user_id')->withPivot('tickets','rules');
    }


    public function checkRule($rule_key) {

        $userRules = $this->participants()->where('user_id',Auth::user()->id)->first()->pivot->rules;

        if($userRules != '')
        foreach(json_decode($userRules) as $key => $rules) {
            if($key == $rule_key) {
                if($rules == false) 
                    $this->joinAvalible = false;

                return $rules;
            }
                
        }
    }
}

app/Http/Controllers/Admin/GiveawayController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use Storage;
use App\Giveaway;
use App\GiveawayRules;
class GiveawayController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth','isAdmin']);
    }

    public function list() {
        $quests = Giveaway::all();
        
        

        return view('admin.giveaway.list',compact('quests'));
    }

    public function show($id) {
        $quest = Giveaway::find($id);

        return view('admin.giveaway.show',compact('quest'));
    }

    public function create() {
        $rules = GiveawayRules::all();
        return view('admin.giveaway.create',compact('rules'));
    }

    public function store(Request $request) {
        $data = $request->all();
        

        $mainImg  = $request->file('main_img');

        $mainImg = Storage::putFileAs(
            'public/giveaway', $request->file('main_img'), time().'-'.str_replace(' ','-',$data['title'])
        );
        
        $data['main_img'] = $mainImg;

        $carouselImages = $request->file('carousel_img');
        $count = 0;
        
        if(count($carouselImages) > 0) {
            foreach($carouselImages as $image) {
                $carousel[] = Storage::putFileAs(
                    'public/giveaway',$image, time().'-carousel-'.$count.'-'.str_replace(' ','-',$data['title'])
                );
                $count++;
            }
            $data['carousel_img'] = json_encode($carousel);
        } else {
            $data['carousel_img'] = '';
        }
        

        $data['ending_at'] = date('Y-m-d H:i:s',strtotime($data['ending_at'].' '.$data['ending_time']));

        
        $giveaway = Giveaway::create($data);

        $giveaway->rules()->attach($data['rules']);

        return redirect()->back();  
    }

    public function activate($id) {
        $quest = Giveaway::find($id);

        $quest->status = 1;
        $quest->save();
        return redirect()->back();
    }
    public function deactivate($id) {
        $quest = Giveaway::find($id);

        $quest->status = 0;
        $quest->save();
        return redirect()->back();
    }
    public function edit($id) {
        $quest = Giveaway::find($id);

        return view('admin.giveaway.edit',compact('quest'));
    }

    public function update(Request $request,$id) {
        $quest = Giveaway::find($id);
        $data = $request->all();

        return redirect()->back();
    }

    public function delete($id) {
        $post = Giveaway::find($id);

        $post->delete();

        return redirect()->route('admin.giveaway.list');
    }

}

app/Http/Controllers/Giveaway/GiveawayController.php
<?php

namespace App\Http\Controllers\Giveaway;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Giveaway;
use Auth;
use GiveawayRules;

class GiveawayController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */

      public function list() {

         $giveaways = Giveaway::all();

         return view('giveaway.list',compact('giveaways'));
      }

     public function show($id) {

        $giveaway = Giveaway::find($id);
        
         $rules = array();
         $giveaway->participants()->sync(Auth::user()->id,false);

         
         if($giveaway->participants()->where('user_id',Auth::user()->id)->where('joined',0)->exists()) {
            
            foreach($giveaway->rules as $rule) {
               
               $result = GiveawayRules::checkRule($rule,$giveaway->id);

               $rules[$rule->rule_key] = $result;
            }
            $giveaway->participants()->updateExistingPivot(Auth::user()->id,['rules'=> json_encode($rules)]); 
         }
         


        
        
        return view('giveaway.show',compact('giveaway'));
     }

     public function join($id) {
        $giveaway = Giveaway::find($id);
        $user = Auth::user();
        $userTickets = $user->tickets + $user->tmp_tickets;
        $user->tmp_tickets = 0;
        $user->save();
        $giveaway->participants()->updateExistingPivot(Auth::user()->id,['joined'=>1,'tickets'=>$userTickets]);

        return redirect()->back();
     }
}

app/Http/Controllers/Giveaway/Tickets/TicketsController.php
<?php

namespace App\Http\Controllers\Giveaway\Tickets;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\GiveawayQuests;
use Auth;


class TicketsController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */

     public function list() {
        
        $quests = GiveawayQuests::where('status',1)->get();


        $questsStatic = $quests->where('type',1);
        $questsAdditional = $quests->where('type',2);

        //sprawdzenie czy quest jest zrobiony
        $userQuestsStatic = Auth::user()->questDone->where('type',1);
        $userQuestsAdditional = Auth::user()->questDone->where('type',2);
        
        $pointsStatic = 0;
        $pointsAdditional = 0;


        foreach($userQuestsStatic as $quest) {
            $pointsStatic += $quest->points;
        }

        foreach($userQuestsAdditional as $quest) {
            $pointsAdditional += $quest->points;
        }

        $questsStatic = $questsStatic->diff($userQuestsStatic);
        $questsAdditional = $questsAdditional->diff($userQuestsAdditional);

        return view('giveaway.tickets.tickets',compact('questsStatic','questsAdditional','pointsAdditional','pointsStatic','userQuestsStatic','userQuestsAdditional'));
     }

     
}

resources/views/giveaway/list.blade.php
@extends('layouts.app')

@section('content')


<div id="giveaway-list-page" class="content">

    <div class="container-fluid">


        <div class="row">
            <div class="col-12">
                <h1 class="mb30">Giveaway</h1>
            </div>
        </div>

        @if($giveaways->where('status',1)->isEmpty())
        <div class="row">
            <div class="col-12">
                <div class="alert alert-warning mb30">Brak aktywnych giveaway.</div>
            </div>
        </div>
        @else 
        <div class="row">
            <div class="col-12">
                <div class="card-deck">
                    @foreach($giveaways as $giveaway)
                        <div class="card">
                            <a href="{{route('giveaway.show',['id'=>$giveaway->id])}}">
                                @if($giveaway->main_img != '')
                                    <img src="{{ Storage::url($giveaway->main_img) }}" class="card-img-top" alt="Giveaway Image">
                                @else
                                    <img src="{{ asset('images/giveaway/giveaway-default.jpg') }}" class="card-img-top" alt="Giveaway Image">
                                @endif
                            </a>
                            <div class="card-body p10 pt20">
                                <h3 class="card-title">{{$giveaway->title}}</h3>
                                <p class="text-muted mb0"><small>{{date('d.m.Y H:i:s',strtotime($giveaway->ending_at))}}</small></p>
                            </div>
                            <div class="card-footer">
                                
                                @if($giveaway->participants()->where('user_id',Auth::user()->id)->Where('joined',1)->exists())
                                    <a href="{{route('giveaway.show',['id'=>$giveaway->id])}}" class="btn btn-success">Dołączono!</a>
                                @else
                                    <a href="{{route('giveaway.show',['id'=>$giveaway->id])}}" class="btn btn-primary">Dołącz do giveaway!</a>
                                @endif
                            </div>
                        </div>
                    @endforeach
                </div>
            </div>
        </div>
        @endif

        <div class="row">
            <div class="col-12">
                <div class="alert alert-info mb30">
                    <h4>Zostań sponsorem!</h4>
                    <p class="mb0">Jeżeli jesteś zainteresowany promocją swojej marki i chcesz ufundować nagrodę na giveaway, zajrzyj do działu <a href="#" class="highlight">współpraca</a> i skontaktuj się z nami. Zapraszamy!</p>
                </div>
            </div>
        </div>


        <div class="row">
            <div class="col-12">
                <h1 class="mb30">Archiwalne giveaway</h1>
            </div>
        </div>

        @if($giveaways->where('status',3)->count() > 0)
        <div class="row">
            <div class="col-12">
                <div class="card-deck">
                    @foreach($giveaway->where('status',3) as $giveaway)
                    <!-- pojedynczy wynik / start -->
                    <div class="card">
                        <a href="{{route('giveaway.show',['id'=>$giveaway->id])}}">
                        @if($giveaway->main_img != '')
                            <img src="{{ Storage::url($giveaway->main_img) }}" class="card-img-top" alt="Giveaway Image">
                        @else
                            <img src="{{ asset('images/giveaway/giveaway-default.jpg') }}" class="card-img-top" alt="Giveaway Image">
                        @endif
                        </a>
                        <div class="card-body p10 pt20">
                            <h3 class="card-title">{{$giveaway->title}}</h3>
                            <p class="text-muted mb0"><small>{{date('d.m.Y H:i:s',strtotime($giveaway->ending_at))}}</small></p>
                        </div>
                        <div class="card-footer text-center">
                            <i class="fas fa-crown"></i> <a href="#" class="highlight">{nickWinnera}</a>
                        </div>
                    </div>
                    <!-- pojedynczy wynik / koniec -->
                    @endforeach
                    <!-- pojedynczy wynik / start -->
                    
                </div>
            </div>

            <!--<div class="col-12 mb30">
                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center">
                        <li class="page-item disabled">
                            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
                        </li>
                        <li class="page-item">
                            <span class="page-link">
                                1
                                <span class="sr-only">(current)</span>
                            </span>
                        </li>
                        <li class="page-item"><a class="page-link highlight" href="#">2</a></li>
                        <li class="page-item"><a class="page-link highlight" href="#">3</a></li>
                        <li class="page-item">
                            <a class="page-link highlight" href="#">Next</a>
                        </li>
                    </ul>
                </nav>
            </div>-->
        </div>
        @else 
            <div class="row">
                <div class="col-12">
                    <div class="alert alert-warning mb30">Brak archiwalnych giveaway.</div>
                </div>
            </div>
        @endif


    </div>

</div>

@endsection

resources/views/giveaway/show.blade.php
@extends('layouts.app')

@section('content')
<script type="text/javascript" src="{{asset('js/html5gallery.js')}}"></script>
<div id="giveaway-page" class="content">

    <div class="container-fluid">

        <div class="row">

            <div class="col-12">
                <h1 class="mb30">{{$giveaway->title}}</h1>
            </div>

            <div class="col-12 mb30">
                Losowanie: <span class="text-nowrap">{{date('d.m.Y H:i:s',strtotime($giveaway->ending_at))}}</span>
            </div>

            <div class="col mb30">
                <p>{{$giveaway->description}}</p>    
            </div>

            <div class="col-lg-auto mb30">


                <!-- A wrapper DIV to center the Gallery -->
                @if($giveaway->carousel_img != NULL)
                <div style="text-align:center;" class="d-sm-none">
                    <!-- Define the Div for Gallery -->
                    <!-- 1. Add class html5gallery to the Div -->
                    <!-- 2. Define parameters with HTML5 data tags -->
                    <div style="display:none;margin:0 auto;" class="html5gallery" data-skin="horizontal" data-width="220" data-height="130" data-resizemode="fill">
                        <!-- Add images to Gallery -->
                        
                        @foreach(json_decode($giveaway->carousel_img) as $image)
                        <a href="{{ Storage::url($image) }}"><img src="{{ Storage::url($image) }}" alt=""></a>
                        @endforeach
                        
                       
                    </div>
                </div>
                @endif
                @if($giveaway->carousel_img != NULL)
                <!-- A wrapper DIV to center the Gallery -->
                <div style="text-align:center;" class="d-none d-sm-block d-lg-none">
                    <!-- Define the Div for Gallery -->
                    <!-- 1. Add class html5gallery to the Div -->
                    <!-- 2. Define parameters with HTML5 data tags -->
                    <div style="display:none;margin:0 auto;" class="html5gallery" data-skin="horizontal" data-width="470" data-height="278" data-resizemode="fill">
                            
                            @foreach(json_decode($giveaway->carousel_img) as $image)
                            <a href="{{ Storage::url($image) }}"><img src="{{ Storage::url($image) }}" alt=""></a>
                            @endforeach
                            
                        
                    </div>
                </div>
                @endif
                @if($giveaway->carousel_img != NULL)
                <!-- A wrapper DIV to center the Gallery -->
                <div style="text-align:center;" class="d-none d-lg-block">
                    <!-- Define the Div for Gallery -->
                    <!-- 1. Add class html5gallery to the Div -->
                    <!-- 2. Define parameters with HTML5 data tags -->
                    <div style="display:none;margin:0 auto;" class="html5gallery" data-skin="horizontal" data-width="560" data-height="331" data-resizemode="fill">
                        <!-- Add images to Gallery -->
                        
                        @foreach(json_decode($giveaway->carousel_img) as $image)
                        <a href="{{ Storage::url($image) }}"><img src="{{ Storage::url($image) }}" alt=""></a>
                        @endforeach
                        
                       
                    </div>
                </div>
                @endif

            </div>


            <div class="col-12 mb30">
                <h4>WARUNKI UDZIAŁU</h4> 
                <ul>
                    @foreach($giveaway->rules as $rule)
                        <li>{{$rule->rule_name}}  @if($giveaway->checkRule($rule->rule_key))<i class="fas fa-check-circle text-success"></i>@else<i class="fas fa-times-circle text-danger"></i>@endif</li>
                    
                    @endforeach
                </ul>
            </div>
            
            @if($giveaway->status == 1)
                @if($giveaway->participants()->where('user_id',Auth::user()->id)->Where('joined',1)->exists())
                
                    <div class="col-12 mb30 text-center">
                        <div class="alert alert-info">
                            <p class="text-success"><i class="fas fa-check fa-2x"></i><br>Dołączyłeś do giveawaya!</p>
                            <?php
                                $allParticipants = $giveaway->participants()->where('joined',1)->count();
                                $allTickets = $giveaway->participants->sum('tickets');
                                $myTickets = $giveaway->participants()->where("user_id",Auth::user()->id)->first()->pivot->tickets;
                            ?>

                            <p>Wszyscy uczestnicy: {{$allParticipants}}<br>
                                Wszystkie tickety: {{$allTickets}}<br>
                                Twoje tickety: {{$myTickets}}<br>Twoja szansa: {{round(($myTickets/$allTickets)*100,2)}}%</p>
                            <p>Zwiększ swoje szanse zdobywając <a href="#" class="highlight">więcej ticketów.</a></p>
                        </div>
                    </div>
                @else 
                    <div class="col-12 mb30 text-center">
                        <div class="alert alert-info">
                            <p>Twoje tickety: {{Auth::user()->tickets+Auth::user()->tmp_tickets}}<br> Zwiększ swoje szanse zdobywając <a href="#" class="highlight">więcej ticketów.</a></p>
                            @if($giveaway->joinAvalible)
                                <a href="{{route('giveaway.join',['id'=>$giveaway->id])}}"class="btn btn-primary btn-lg"><strong>DOŁĄCZ DO GIVEAWAY!</strong></a>
                            @else
                                <p class="mb5 text-danger">Nie spełniasz wszystkich warunków.</p>
                            @endif
                            
                            
                        </div>
                    </div>
                @endif
            @elseif($giveaway->status == 3)
             <div class="col-12 mb30 text-center">
                <div class="alert alert-info">
                    <p class="mt15"><i class="fas fa-crown fa-2x"></i><br>Zwycięzca: <a href="#" class="highlight">{Nickgracza}</a></p>
                </div>
            </div>
            @endif
        </div>

    </div>
    
</div>

@endsection