routes/web.php
                    broadcast(new \App\Events\LobbyStatusChanged($user->id,$info));
            }
            
        
    }
});

Route::get('/poczekalnia/leave/{user_id}', function($user_id) {
    
    Cache::forget('user-is-in-lobby-'.$user_id);
    Cache::forget('lobby-status-'.$user_id);

    if(App::environment('local'))
        $keys = Redis::keys('laravel_cache:user-is-online-*');
    else {
        $keys = Redis::keys('bazagraczy_cache:user-is-online-*');
    }

    $users = array();
    foreach($keys as $user) {
        $split = explode('-',$user);

        $users[] = array_pop($split);
        
    }

    if(!empty($users)) {
        
        $info = [
            'user_id' => $user_id,
            'status' => 'leave',
            'game_name' => Auth::user()->selectedGame()['game'],
            'platform_name' => Auth::user()->selectedGame()['platform'],
        ];

        $users = User::find($users);

        if($users)
            foreach($users as $user){
                if($user->id != Auth::user()->id)
                    broadcast(new \App\Events\LobbyStatusChanged($user->id,$info));
            }
            
        
    }
});

Route::get('/poczekalnia/set/{status}/{user_id}', function($status,$user_id){
    if(Cache::has('lobby-status-'.$user_id)) {
        $cachedStatus = Cache::get('lobby-status-'.$user_id);
        
        if($cachedStatus != $status) {
            Cache::forever('lobby-status-'.$user_id,$status);
        } 
    } else {
        Cache::forever('lobby-status-'.$user_id,$status);
    }

    // broadcast to all online users status changed ... 
    
    if(App::environment('local'))
        $keys = Redis::keys('laravel_cache:user-is-online-*');
    else {
        $keys = Redis::keys('bazagraczy_cache:user-is-online-*');
    }

    $users = array();
    foreach($keys as $user) {
        $split = explode('-',$user);

        $users[] = array_pop($split);
        
    }

    if(!empty($users)) {
        
        $info = [
            'user_id' => $user_id,
            'status' => $status,
            'game_name' => Auth::user()->selectedGame()['game'],
            'platform_name' => Auth::user()->selectedGame()['platform'],
        ];

        $users = User::find($users);

        if($users)
            foreach($users as $user){
                if($user->id != Auth::user()->id)
                    broadcast(new \App\Events\LobbyStatusChanged($user->id,$info));
            }
            
        
    }

    return response()->json(['status'=>$status]);
})->name('lobbystatus');

Route::get('/poczekalnia/mark/{status}/{user_id}','Lobby\LobbyController@markInfo')->name('lobby.mark.info');

Route::post('/poczekalnia/info/set','Lobby\LobbyController@setInfo')->name('lobby.set.info');
Route::get('/poczekalnia','Lobby\LobbyController@show')->name('lobby');


Route::get('/user/{user_id}/status', function($user_id) {
    $user = User::find($user_id);

    $status = $user->getStatus();

    return response()->json($status);
})->name('user_status');

Route::prefix('admin')->name('admin.')->group(function () {

    Route::get('dashboard', 'Admin\AdminController@dashboardShow')->name('dashboard');
    
    Route::get('user', 'Admin\UserController@list')->name('user.list');
    Route::get('user/{id}','Admin\UserController@show')->name('user.show');

    Route::get('menu', 'Admin\AdminController@menuShow')->name('menu');
    Route::get('settings', 'Admin\AdminController@settingsShow')->name('settings');
    Route::get('language', 'Admin\AdminController@languageShow')->name('language');
    Route::get('posts', 'Admin\AdminController@postListShow')->name('posts');
    Route::get('tickets', 'Admin\AdminController@ticketsListShow')->name('tickets');
    
    Route::get('game/list','Admin\GamesController@index')->name('game.list');
    Route::get('game/create', 'Admin\GamesController@createGame')->name('game.create');
    Route::post('game/save', 'Admin\GamesController@saveGame')->name('game.save');
    Route::get('game/scrapper', 'Admin\ScrapperController@index')->name('game.scrapper');
    Route::get('game/scrapper/scrap', 'Admin\ScrapperController@scrap')->name('game.scrapper.scrap');
    Route::get('game/{id}/edit', 'Admin\GamesController@editGame')->name('game.edit');
    Route::post('game/{id}/update', 'Admin\GamesController@updateGame')->name('game.update');
    Route::post('game/{id}/delete', 'Admin\GamesController@deleteGame')->name('game.delete');
    Route::get('game/{id}','Admin\GamesController@showGame')->name('game.show');
    
    
    //Posts
    Route::get('post', 'Admin\PostController@list')->name('post.list');
    Route::get('post/create', 'Admin\PostController@create')->name('post.create');
    Route::post('post/store', 'Admin\PostController@store')->name('post.store');
    Route::get('post/{id}/edit', 'Admin\PostController@edit')->name('post.edit');
    Route::get('post/{id}/update', 'Admin\PostController@update')->name('post.update');
    Route::get('post/{id}/delete', 'Admin\PostController@delete')->name('post.delete');
    Route::get('post/{id}', 'Admin\PostController@show')->name('post.show');

    Route::get('stats/users/append', 'Admin\AdminController@getUsersDailyCount')->name('stats.users.append');
    Route::get('stats/posts/append', 'Admin\AdminController@getPostsDailyCount')->name('stats.posts.append');
    Route::get('stats/comments/append', 'Admin\AdminController@getCommentsDailyCount')->name('stats.comments.append');
    Route::get('stats/logins/append', 'Admin\AdminController@getLoginsDailyCount')->name('stats.logins.append');
    
    Route::get('stats/users/count', 'Admin\AdminDashboardController@countUsers')->name('stats.users.count');

    Route::get('tickets', 'Admin\TicketsController@list')->name('tickets.list');
    Route::get('tickets/{id}', 'Admin\TicketsController@show')->name('tickets.show');
    Route::get('tickets/{id}/close', 'Admin\TicketsController@closeTicket')->name('tickets.close');
    Route::get('tickets/{id}/open', 'Admin\TicketsController@openTicket')->name('tickets.open');
    Route::post('tickets/wyslij','Admin\TicketsController@messageSend')->name('tickets.send');

    Route::get('giveaway', 'Admin\GiveawayController@list')->name('giveaway.list');
    Route::get('giveaway/create', 'Admin\GiveawayController@create')->name('giveaway.create');
    Route::post('giveaway/store', 'Admin\GiveawayController@store')->name('giveaway.store');
    Route::get('giveaway/{id}/edit', 'Admin\GiveawayController@edit')->name('giveaway.edit');
    Route::get('giveaway/{id}/update', 'Admin\GiveawayController@update')->name('giveaway.update');
    Route::get('giveaway/{id}/delete', 'Admin\GiveawayController@delete')->name('giveaway.delete');
    Route::get('giveaway/{id}/activate', 'Admin\GiveawayController@activate')->name('giveaway.activate');
    Route::get('giveaway/{id}/deactivate', 'Admin\GiveawayController@deactivate')->name('giveaway.deactivate');
    Route::get('giveaway/{id}', 'Admin\GiveawayController@show')->name('giveaway.show');

    Route::get('quest', 'Admin\QuestController@list')->name('quest.list');
    Route::get('quest/create', 'Admin\QuestController@create')->name('quest.create');
    Route::post('quest/store', 'Admin\QuestController@store')->name('quest.store');
    Route::get('quest/{id}/edit', 'Admin\QuestController@edit')->name('quest.edit');
    Route::get('quest/{id}/update', 'Admin\QuestController@update')->name('quest.update');
    Route::get('quest/{id}/delete', 'Admin\QuestController@delete')->name('quest.delete');
    Route::get('quest/{id}/activate', 'Admin\QuestController@activate')->name('quest.activate');
    Route::get('quest/{id}/deactivate', 'Admin\QuestController@deactivate')->name('quest.deactivate');
    Route::get('quest/{id}', 'Admin\QuestController@show')->name('quest.show');
});

Route::prefix('helper')->name('help.')->group(function () {
    Route::get('voivodeship', 'HelperController@getVoivodeships')->name('voivodeships');
    Route::get('cities/{voivodeship_id}', 'HelperController@getCities')->name('cities');
    Route::get('games', 'HelperController@getGames')->name('games');
    Route::get('platforms/{game_id}', 'HelperController@getGamesPlatform')->name('platforms');
    Route::get('teams/{clan_id}', 'HelperController@getClanTeams')->name('teams');
    Route::get('members/{clan_id}', 'HelperController@getTeamMembers')->name('members');
    Route::get('set/friends/list','HelperController@setFriendList')->name('friend.list');

});


Route::prefix('mecz')->name('match.')->group(function () {
    Route::prefix('towarzyski')->name('friendly.')->group(function() {
        
        Route::get('stworz','Match\FriendlyController@createFriendly')->name('create');
        Route::post('zapisz','Match\FriendlyController@saveFriendly')->name('save');
        
        Route::get('tablica','Match\FriendlyController@showFriendly')->name('list');
        Route::post('tablica','Match\FriendlyController@doSearching')->name('list.search');
        
        Route::get('zobacz/{id}', 'Match\FriendlyController@showMatch')->name('show');
        Route::get('edytuj/{id}', 'Match\FriendlyController@editMatch')->name('edit');
        Route::post('edytuj','Match\FriendlyController@updateMatch')->name('update');
        Route::get('usun/{ids}','Match\FriendlyController@deleteMatch')->name('delete');
        Route::post('dolacz','Match\FriendlyController@joinMatch')->name('join');
        Route::post('potwierdz','Match\FriendlyController@applyMatch')->name('apply');
        Route::get('akceptuj/{id}','Match\FriendlyController@acceptAplication')->name('accept');
        Route::get('podsumowanie','Match\FriendlyController@confirmFriendly')->name('confirm');
        Route::get('cancel/{id}','Match\FriendlyController@cancelMatch')->name('cancel');

        Route::get('aktywne','Match\FriendlyController@showActive')->name('show.active');
        Route::get('otwarte','Match\FriendlyController@showOpen')->name('show.open');

resources/views/includes/menu/extras.blade.php
<div class="menu-item" onclick="extrasDIV()">
                <i class="fas fa-star"></i>
            </div>
            <script>
                function extrasDIV() {
                    var x = document.getElementById("menu-extras");
                    if (x.style.display === "none") {
                        x.style.display = "block";
                    } else {
                        x.style.display = "none";
                    }
                }
                $(document).ready(function ()
                {
                    $(document).mouseup(function (e)
                    {
                        var subject = $("#menu-extras");

                        if (e.target.id !== subject.attr('id') && !subject.has(e.target).length)
                        {
                            subject.hide();
                        }
                    });
                });
            </script>
<div id="menu-extras" class="menu-div" style="display: none;">
    <div class="menu-div-wrapper">
        <div class="menu-inner">

            <h6 class="dark mt30 mb5">ACHIVMENTS</h6>
            
            <a href="{{route('giveaway.tickets.list')}}">
                <div class="submenu-item">
                    Osiągnięcia
                    <div class="submenu-item-action">
                        <i class="fas fa-chevron-right fa-sm"></i>
                    </div>
                </div>
            </a>
            <h6 class="dark mt30 mb5">GIVEAWAY</h6>
            
            <a href="{{route('giveaway.list')}}">
                <div class="submenu-item">
                    Giveaway'e
                    <div class="submenu-item-action">
                        <i class="fas fa-chevron-right fa-sm"></i>
                    </div>
                </div>
            </a>
        </div>
    </div>
</div>

resources/views/includes/menu/game.blade.php
<div id="menu-menugra" class="menu-div" style="display: none;">
        <div class="menu-div-wrapper">
            <div class="menu-inner">

                <h6 class="dark mt30 mb5">{{Auth::user()->selectedGame()['game']}} <span class="badge badge-muted">{{Auth::user()->selectedGame()['platform']}}</span></h6>
                <a href="{{route('wall')}}">
                    <div class="submenu-item">
                        <i class="fas fa-clipboard-list"></i> Tablica ogłoszeń
                    </div>
                </a>
                <a href="{{route('lobby')}}">
                    <div class="submenu-item">
                        <i class="fas fa-gamepad"></i> Poczekalnia
                    </div>
                </a>
                <a href="{{route('feeds')}}">
                        <div class="submenu-item">
                            <i class="fas fa-newspaper"></i> Aktualności
                        </div>
                    </a>
                <h6 class="dark mt30 mb5">GRACZE I KLANY</h6>
                <a href="{{route('search.search')}}">
                    <div class="submenu-item">
                        <i class="fas fa-search"></i> Wyszukiwarka graczy
                    </div>
                </a>
                <a href="{{route('clan.search')}}">
                    <div class="submenu-item">
                        <i class="fas fa-search"></i> Wyszukiwarka klanów
                    </div>
                </a>
                <a href="{{route('clan.create')}}">
                    <div class="submenu-item">
                        <i class="fas fa-plus-circle"></i> Stwórz klan 
                    </div>
                </a>
                <h6 class="dark mt30 mb5">WOJNY KLANOWE</h6>
                <a href="{{route('match.friendly.list')}}">
                    <div class="submenu-item">
                        <i class="fas fa-clock"></i> Aktualne klanówki
                    </div>
                </a>
                <a href="{{route('match.friendly.show.archive')}}">
                    <div class="submenu-item">
                        <i class="fas fa-history"></i> Archiwalne klanówki
                    </div>
                </a>
                <a href="{{route('match.friendly.create')}}">
                    <div class="submenu-item">
                        <i class="fas fa-plus-circle"></i> Stwórz klanówkę
                    </div>
                </a>

            </div>
        </div>
    </div>

resources/views/includes/menu/info.blade.php
<div id="menu-info" class="menu-div" style="display: none;">
    <div class="menu-div-wrapper">
        <div class="menu-inner">

            <h6 class="dark mt30 mb5">BAZAGRACZY.PL</h6>
            <a href="{{route('kontakt')}}">
                <div class="submenu-item">
                    Kontakt
                    <div class="submenu-item-action">
                        <i class="fas fa-chevron-right fa-sm"></i>
                    </div>
                </div>
            </a>
            <a href="{{route('regulamin')}}">
                <div class="submenu-item">
                    Regulamin
                    <div class="submenu-item-action">
                        <i class="fas fa-chevron-right fa-sm"></i>
                    </div>
                </div>
            </a>
            <a href="{{route('polityka_prywatnosci')}}">
                <div class="submenu-item">
                    Polityka prywatności
                    <div class="submenu-item-action">
                        <i class="fas fa-chevron-right fa-sm"></i>
                    </div>
                </div>
            </a>

            <div class="copyright">
                Korzystając z serwisu<br>
                akceptujesz jego <a href="#">Regulamin</a>.<br>
                © BAZAGRACZY.pl 2018<br>
                Wszelkie prawa zastrzeżone.<br>
            </div>

        </div>
    </div>
</div>

resources/views/includes/menu/profil.blade.php
<div id="menu-profil" class="menu-div" style="display: none;">
        <div class="menu-div-wrapper">
            <div class="menu-inner">

                <h6 class="dark mt20 mb5">PROFIL</h6>
                <div class="submenu-item-wrapper">
                    <a href="/profil/{{Auth::user()->id}}">
                        <div class="submenu-item">
                            <i class="fas fa-user"></i> Zobacz profil</span>
                        </div>
                    </a>
                </div>
                <?php
                $notifications = count(Auth::user()->unreadNotifications);
                ?>
                <div class="submenu-item-wrapper">
                    <a href="{{route('profile.notifications.show')}}">
                        <div class="submenu-item">
                            <i class="fas fa-bullhorn"></i> Powiadomienia @if($notifications > 0)<span class="badge badge-danger"><span class="notification-count1">{{$notifications}}</span></span>@else<span class="badge badge-danger" style='display:none;' id='notification_show1'><span class='notification-count1'></span></span>@endif
                        </div>
                    </a>
                </div>
                <div class="submenu-item-wrapper">
                    <a href="{{route('profile.library')}}">
                        <div class="submenu-item">
                            <i class="fas fa-gamepad"></i> Biblioteka gier</span>
                        </div>
                    </a>
                </div>
                <div class="submenu-item-wrapper">
                    <a href="{{route('profile.edit')}}">
                        <div class="submenu-item">
                            <i class="fas fa-address-card"></i> Edytuj profil</span>
                        </div>
                    </a>
                </div>
                <div class="submenu-item-wrapper">
                    <a href="{{route('profile.avatar')}}">
                        <div class="submenu-item">
                            <i class="fas fa-user-circle"></i> Edytuj avatar</span>
                        </div>
                    </a>
                </div>
                <div class="submenu-item-wrapper">
                    <a href="{{route('profile.account')}}">
                        <div class="submenu-item">
                            <i class="fas fa-key"></i> Dane logowania</span>
                        </div>
                    </a>
                </div>
                <div class="submenu-item-wrapper">
                    <a href="{{route('profile.settings')}}">
                        <div class="submenu-item">
                            <i class="fas fa-cog"></i> Ustawienia</span>
                        </div>
                    </a>
                </div>

                <h6 class="dark mt20 mb5">GRACZE</h6>
                <a href="{{route('profile.followers')}}">
                    <div class="submenu-item">
                        <i class="fas fa-user-friends"></i> Znajomi
                    </div>
                </a>
                <a href="{{route('profile.blocked')}}">
                    <div class="submenu-item">
                        <i class="fas fa-user-alt-slash"></i> Zablokowani
                    </div>
                </a>

                <h6 class="dark mt20 mb5">KLANY</h6>
                <a href="{{route('clan.list')}}">
                    <div class="submenu-item">
                        <i class="fas fa-user-shield"></i> Moje klany
                        @if(Auth::user()->UserClanAplications())
                            <span  id='clan-join' class="badge badge-danger clan-join">
                                <i class="fas fa-exclamation-circle"></i>
                            </span>
                        @else 
                            <span id='clan-join' class="badge badge-danger clan-join" style="display: none;">
                                <i class="fas fa-exclamation-circle"></i>
                            </span> 
                        @endif
                    </div>
                </a>
                <a href="{{route('clan.create')}}">
                    <div class="submenu-item">
                        <i class="fas fa-plus-circle"></i> Stwórz klan 
                    </div>
                </a>

                <h6 class="dark mt20 mb5">WOJNY KLANOWE</h6>
                <a href="{{route('match.friendly.show.open')}}">
                    <div class="submenu-item">
                        <i class="fas fa-calendar-alt"></i> Moje klanówki 
                        
                        @if(Auth::user()->AllFriendlyMatchesAction())
                            <span  id='match-warning-menu' class="badge badge-danger klany-action">
                                <i class="fas fa-exclamation-circle"></i>
                            </span>
                        @else 
                            <span id='match-warning-menu' class="badge badge-danger klany-action" style="display: none;">
                                <i class="fas fa-exclamation-circle"></i>
                            </span> 
                        @endif
                    </div>
                </a>
                <a href="{{route('match.friendly.create')}}">
                    <div class="submenu-item">
                        <i class="fas fa-plus-circle"></i> Stwórz klanówkę
                    </div>
                </a>

            </div>
        </div>
    </div>